name: radvd-gael
base: core24
version: "v2.20-rc.1-core24"
summary: Router Advertisement Daemon
description: |
  The Router Advertisement Daemon (radvd) is an open-source software product that implements link-local advertisements of IPv6 router addresses and IPv6 routing prefixes using the Neighbor Discovery Protocol (NDP) as specified in RFC 2461.
grade: stable
confinement: strict

platforms:
  arm64:
  armhf:
  amd64:

apps:
  radvd:
    command: radvd.sh
    daemon: forking
    plugs:
    - firewall-control   # Otherwise: Permission denied on /proc/sys/net/ipv6/conf/all/forwarding

parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    stage:
      - radvd.sh

  app:
    plugin: autotools
    source: https://github.com/radvd-project/radvd
    source-tag: v2.20_rc1
    source-type: git
    override-pull: |
      craftctl default
      sed -i '57,62d' configure.ac
    build-packages:
      - build-essential
      - byacc
      - flex
      - libbsd-dev
