name: radvd-gael
base: core24
version: "v2.20+git.878ca6b"
summary: Router Advertisement Daemon
description: |
  The Router Advertisement Daemon (radvd) is an open-source software product that implements link-local advertisements of IPv6 router addresses and IPv6 routing prefixes using the Neighbor Discovery Protocol (NDP) as specified in RFC 2461.
grade: stable
confinement: strict

platforms:
  arm64:
  armhf:
  amd64:

apps:
  radvd:
    command: radvd.sh
    daemon: forking
    plugs:
      - firewall-control   # To work around permission denied on /proc/sys/net/ipv6/conf/all/forwarding

  radvdump:
    command: usr/local/sbin/radvdump
    plugs:
      - network-control   # To allow listening to IPv6-ICMP

parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    stage:
      - radvd.sh

  app:
    plugin: autotools
    source: https://github.com/radvd-project/radvd
      #    source-tag: v2.20
    source-commit: 878ca6bc5074b3427a2eb94a4c4a8b1f34b7bfed
    source-type: git
    build-packages:
      - build-essential
      - byacc
      - flex
      - libbsd-dev
      - pkg-config
      - check
    stage:
      - usr/local/sbin
      - -usr/local/share
