name: radvd-gael
base: core22
version: "2.19+git.c8a11fd-core22"
summary: Router Advertisement Daemon
description: |
  The Router Advertisement Daemon (radvd) is an open-source software product that implements link-local advertisements of IPv6 router addresses and IPv6 routing prefixes using the Neighbor Discovery Protocol (NDP) as specified in RFC 2461.
grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  radvd:
    command: radvd.sh
    daemon: forking
    plugs:
    - firewall-control   # Otherwise: Permission denied on /proc/sys/net/ipv6/conf/all/forwarding

parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    stage:
      - radvd.sh

  app:
    plugin: autotools
    source: https://github.com/radvd-project/radvd
    source-commit: c8a11fdc1e63d78b8fe89554192e2452185a65f3
    source-type: git
    override-pull: |
      snapcraftctl pull
      sed -i '57,62d' configure.ac
    build-packages:
      - build-essential
      - byacc
      - flex
